# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false
# Изменяет текущую временную зону.
before_install:
- export TZ=Europe/Moscow
- date
# Отправлять уведомление на почтуmailto:youremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - mailto:rusanov_roman@icloud.com
    on_success: never # default: change
    on_failure: always # default: always